### ISSUE TITLE
Exception for  Stellaris 2.3.3 at "00_scripted_triggers.txt"

### ISSUE THREAD

**Issue by Keepidroid** [turanar/stellaris-config-parser#1]
Stellaris is updated to 2.3.3, and I want to translate the tech tree to another language, but got this exception:

`Exception in thread "main" org.antlr.v4.runtime.misc.ParseCancellationException: line 651:32 token recognition error at: '$'`

I'm not familiar with ANTLR  but it seems like I need the Stellaris.g4 file to regenerate the parser.

**Comment by turanar** [comment]
Ah yeah ... i need to commit my last update on this project. I will do that tonight

**Comment by turanar** [comment]
See the code for Stellaris 2.2+ here : https://github.com/turanar/stellaris-technology

This project is deprecated. I will update the tech-tree project to point to the right parser.

**Comment by Keepidroid** [comment]
I will try. thanks

**Comment by Keepidroid** [comment]
btw,  your tech-tree project has a wrong link point to Stellaris 2.3.0 but harmless.

`<li><a href="wolfe-2.3-0/index.html">Stellaris 2.3.0</a></li>`

it should be 2.3.0, not 2.3-0
